name: initial
description: A new Flutter project. 
publish_to: 'none' 
 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-443.0.dev <3.0.0' 
dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0 
  sizer: ^2.0.15
  get: ^4.6.5
  google_fonts: ^3.0.1
  flutter_easyloading: ^3.0.5
  container_tab_indicator: ^0.3.0
  flutter_svg: 

dev_dependencies:
  flutter_test:
    sdk: flutter 
  
flutter: 
  uses-material-design: true
  
  assets:
    - assets/  
    - assets/images/
    - assets/icons/ 
   
  
 